# -*- coding: utf-8 -*-
"""unflutter_apply.py — IDA idalib script

Reads flutter_meta.json produced by `unflutter meta`, applies:
  1. All struct types (DartThread + Dart classes) via parse_decls — one shot
  2. Function creation + renaming
  3. Function signatures with typed this pointers referencing structs
  4. EOL comments (THR fields, PP pool refs, string refs)
  5. Hex-Rays decompilation of focus functions

Pattern follows IL2CppDumper: generate C header, parse_decls(), apply_type().

Usage:
  python3 unflutter_apply.py <libapp.so> <flutter_meta.json> [<output_dir>]

Requires:
  - IDA Pro with idalib (idapro Python package)
  - Hex-Rays decompiler for ARM64 (for decompilation phase)
"""

import json
import os
import sys
import time


def log(msg):
    sys.stderr.write(msg + "\n")
    sys.stderr.flush()


def sanitize(name):
    """Sanitize a name for use as C identifier or filename."""
    out = []
    for ch in name:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    s = "".join(out)
    # C identifiers can't start with a digit.
    if s and s[0].isdigit():
        s = "_" + s
    return s[:120] if len(s) > 120 else s


def sanitize_filename(name):
    """Sanitize for filenames (allows dots and hyphens)."""
    out = []
    for ch in name:
        if ch.isalnum() or ch in ("_", "-", "."):
            out.append(ch)
        else:
            out.append("_")
    s = "".join(out)
    return s[:120] if len(s) > 120 else s


def resolve_meta_path(argv):
    """Resolve flutter_meta.json path from argv or relative to this script."""
    if len(argv) >= 3 and argv[2]:
        return argv[2]
    # Standalone mode: look for ../flutter_meta.json relative to this script.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    candidate = os.path.join(script_dir, "..", "flutter_meta.json")
    if os.path.exists(candidate):
        return candidate
    return None


def main():
    if len(sys.argv) < 2:
        log("Usage: python3 unflutter_apply.py <libapp.so> [<flutter_meta.json>] [<output_dir>]")
        sys.exit(1)

    binary_path = sys.argv[1]
    meta_path = resolve_meta_path(sys.argv)
    out_dir = sys.argv[3] if len(sys.argv) > 3 else None

    if not os.path.exists(binary_path):
        log("ERROR: binary not found: %s" % binary_path)
        sys.exit(1)
    if meta_path is None or not os.path.exists(meta_path):
        log("ERROR: flutter_meta.json not found. Pass as argument or place script in <output>/ida/")
        sys.exit(1)

    log("unflutter_apply (IDA): loading %s" % meta_path)
    with open(meta_path, "r") as f:
        meta = json.load(f)

    # ---- Open database ----
    log("Opening binary in IDA: %s" % binary_path)
    import idapro
    idapro.enable_console_messages(False)

    result = idapro.open_database(binary_path, True)
    if result != 0:
        # Try fresh — delete stale database files.
        for ext in (".i64", ".idb", ".id0", ".id1", ".id2", ".nam", ".til"):
            p = binary_path + ext
            if os.path.exists(p):
                os.remove(p)
        result = idapro.open_database(binary_path, True)
        if result != 0:
            log("ERROR: failed to open database (code %d)" % result)
            sys.exit(1)
    log("  database opened")

    # ---- Import IDA modules (only after db is open) ----
    import ida_auto
    import ida_funcs
    import ida_typeinf
    import idautils
    import idc

    has_decompiler = False
    try:
        import ida_hexrays
        has_decompiler = ida_hexrays.init_hexrays_plugin()
    except Exception:
        pass
    log("  decompiler: %s" % ("yes" if has_decompiler else "no"))

    # ---- Wait for auto-analysis ----
    log("Waiting for auto-analysis...")
    t0 = time.time()
    ida_auto.auto_wait()
    log("  done (%.1fs)" % (time.time() - t0))

    pointer_size = meta.get("pointer_size", 8)
    log("  pointer_size: %d" % pointer_size)

    stats = {
        "functions": len(meta.get("functions", [])),
        "func_created": 0,
        "func_named": 0,
        "func_failed": 0,
        "sig_applied": 0,
        "sig_failed": 0,
        "comments": 0,
        "comment_failed": 0,
        "decompiled": 0,
        "decompile_failed": 0,
    }

    # ================================================================
    # Phase 1: Generate C header and parse all types at once
    # ================================================================
    # Like IL2CppDumper: build one big .h, parse_decls() in one shot.
    thr_fields = meta.get("thr_fields", [])
    classes = meta.get("classes", [])
    struct_names = {}  # dart class_name -> C struct name

    header_lines = []
    header_lines.append("// Auto-generated by unflutter for IDA")
    header_lines.append("")

    # DartThread struct.
    if thr_fields:
        header_lines.append(build_dart_thread_struct(thr_fields))
        header_lines.append("")

    # Dart class structs.
    for cls in classes:
        cname = cls.get("class_name", "")
        if not cname:
            continue
        sname = "Dart_" + sanitize(cname)
        size = cls.get("instance_size", 0)
        if size <= 0:
            continue
        fields = cls.get("fields", [])
        header_lines.append(build_class_struct(sname, size, fields, pointer_size))
        header_lines.append("")
        struct_names[cname] = sname

    header = "\n".join(header_lines)

    if header.strip():
        # Write header to disk for reference / debugging.
        header_path = os.path.splitext(meta_path)[0] + "_types.h"
        with open(header_path, "w") as hf:
            hf.write(header)
        log("Phase 1: wrote %s (%d bytes)" % (header_path, len(header)))

        # Parse all types in one shot (like IL2CppDumper's parse_decls).
        nerr = ida_typeinf.idc_parse_types(header, 0)
        if nerr == 0:
            type_count = 1 + len(struct_names)  # DartThread + classes
            log("  parsed %d struct types (0 errors)" % type_count)
        else:
            log("  WARN: %d parse errors (some structs may be missing)" % nerr)
    else:
        log("Phase 1: skipped (no types to create)")

    # ================================================================
    # Phase 2: Create/rename functions
    # ================================================================
    functions = meta.get("functions", [])
    log("Phase 2: creating/renaming %d functions..." % len(functions))
    for entry in functions:
        addr = int(entry["addr"], 16)
        name = entry["name"]
        size = entry.get("size", 0)

        # Ensure a function starts at exactly this address.
        # Dart has checked/unchecked entry points — IDA may merge them
        # into one function. Split if our addr is mid-function.
        fn = ida_funcs.get_func(addr)
        if fn is not None and fn.start_ea != addr:
            # Our address is inside a larger function — split it.
            ida_funcs.del_func(fn.start_ea)
            # Re-create the head portion.
            ida_funcs.add_func(fn.start_ea, addr)
            fn = None  # fall through to create our function

        if fn is None:
            end = addr + size if size > 0 else addr
            if ida_funcs.add_func(addr, end):
                stats["func_created"] += 1
            else:
                idc.create_insn(addr)
                if ida_funcs.add_func(addr, end):
                    stats["func_created"] += 1
                else:
                    stats["func_failed"] += 1

        # Set name (SN_NOWARN | SN_NOCHECK — same pattern as IL2CppDumper).
        flags = idc.SN_NOWARN | idc.SN_NOCHECK
        if not idc.set_name(addr, name, flags):
            fallback = "%s_%x" % (name, addr)
            idc.set_name(addr, fallback, flags)
        stats["func_named"] += 1

    log("  created=%d named=%d failed=%d" % (
        stats["func_created"], stats["func_named"], stats["func_failed"]))

    # Re-run analysis after function creation.
    log("  re-analyzing...")
    ida_auto.auto_wait()

    # ================================================================
    # Phase 3: Apply function signatures
    # ================================================================
    # Like IL2CppDumper: apply_type(addr, parse_decl(signature, 0), 1)
    log("Phase 3: applying function signatures...")
    for entry in functions:
        addr = int(entry["addr"], 16)
        owner = entry.get("owner", "")
        pc = entry.get("param_count", 0)
        name = entry["name"]

        proto = build_function_prototype(name, owner, pc, struct_names)
        if not proto:
            continue

        try:
            decl = idc.parse_decl(proto, 0)
            if decl:
                if idc.apply_type(addr, decl, 1) != False:
                    stats["sig_applied"] += 1
                else:
                    stats["sig_failed"] += 1
            else:
                stats["sig_failed"] += 1
        except Exception:
            stats["sig_failed"] += 1

    log("  applied=%d failed=%d" % (stats["sig_applied"], stats["sig_failed"]))

    # ================================================================
    # Phase 4: Set comments
    # ================================================================
    comments = meta.get("comments", [])
    log("Phase 4: setting %d comments..." % len(comments))
    for entry in comments:
        addr = int(entry["addr"], 16)
        text = entry["text"]
        try:
            # Repeatable comment (1) so it shows in decompiler too.
            idc.set_cmt(addr, text, 1)
            stats["comments"] += 1
        except Exception:
            stats["comment_failed"] += 1
    log("  set=%d failed=%d" % (stats["comments"], stats["comment_failed"]))

    # ================================================================
    # Phase 5: Decompile focus functions
    # ================================================================
    focus = meta.get("focus_functions", [])
    if out_dir and focus and has_decompiler:
        log("Phase 5: decompiling %d focus functions..." % len(focus))
        if not os.path.exists(out_dir):
            os.makedirs(out_dir)

        name_by_addr = {}
        owner_by_addr = {}
        for entry in functions:
            a = entry["addr"]
            name_by_addr[a] = entry["name"]
            if entry.get("owner"):
                owner_by_addr[a] = entry["owner"]

        index = []
        for addr_str in focus:
            addr = int(addr_str, 16)
            fn = ida_funcs.get_func(addr)
            if fn is None:
                index.append({
                    "addr": addr_str,
                    "name": name_by_addr.get(addr_str, "unknown"),
                    "file": None,
                    "decompile_ok": False,
                    "reason": "no_function",
                })
                stats["decompile_failed"] += 1
                continue

            fn_name = idc.get_func_name(fn.start_ea)
            try:
                cfunc = ida_hexrays.decompile(fn.start_ea)
                if cfunc is None:
                    raise Exception("decompile returned None")

                # Retype Dart registers for readable output.
                # First pass: set names and types, save, re-decompile.
                # Second pass: re-apply names (re-decompile may reassign).
                if _retype_ida_registers(
                        cfunc, fn.start_ea, ida_hexrays, thr_fields):
                    cfunc = ida_hexrays.decompile(fn.start_ea)
                    if cfunc is None:
                        raise Exception("re-decompile returned None")
                    # Re-apply names on the fresh cfunc (types persist
                    # via save_user_lvars but names may need refreshing).
                    _retype_ida_registers(
                        cfunc, fn.start_ea, ida_hexrays, thr_fields)

                c_code = str(cfunc)

                safe_name = addr_str.replace("0x", "") + "_" + sanitize_filename(fn_name)
                owner = owner_by_addr.get(addr_str, "")
                if owner:
                    sub = sanitize_filename(owner)
                    sub_dir = os.path.join(out_dir, sub)
                    if not os.path.exists(sub_dir):
                        os.makedirs(sub_dir)
                    out_file = os.path.join(sub, safe_name + ".c")
                else:
                    out_file = safe_name + ".c"

                with open(os.path.join(out_dir, out_file), "w") as cf:
                    cf.write(c_code)

                index.append({
                    "addr": addr_str,
                    "name": fn_name,
                    "file": out_file,
                    "decompile_ok": True,
                })
                stats["decompiled"] += 1
            except Exception as e:
                index.append({
                    "addr": addr_str,
                    "name": fn_name,
                    "file": None,
                    "decompile_ok": False,
                    "reason": str(e)[:100],
                })
                stats["decompile_failed"] += 1

        with open(os.path.join(out_dir, "index.json"), "w") as idx:
            json.dump(index, idx, indent=2)
        log("  decompiled=%d failed=%d" % (stats["decompiled"], stats["decompile_failed"]))
    elif not has_decompiler:
        log("Phase 5: skipped (no Hex-Rays)")
    elif not out_dir:
        log("Phase 5: skipped (no output dir)")
    else:
        log("Phase 5: skipped (no focus functions)")

    # ================================================================
    # Save and close
    # ================================================================
    log("Saving database...")
    idapro.close_database(1)

    log("DONE: functions=%d created=%d named=%d structs=%d "
        "sigs=%d comments=%d decompiled=%d decomp_failed=%d" % (
            stats["functions"],
            stats["func_created"],
            stats["func_named"],
            len(struct_names) + (1 if thr_fields else 0),
            stats["sig_applied"],
            stats["comments"],
            stats["decompiled"],
            stats["decompile_failed"],
        ))


# ============================================================
# C header generation
# ============================================================

def build_dart_thread_struct(thr_fields):
    """Build DartThread struct as C declaration."""
    sorted_fields = sorted(thr_fields, key=lambda f: f["offset"])
    max_off = max(f["offset"] for f in sorted_fields)
    struct_size = max_off + 8

    lines = ["struct DartThread {"]
    prev_end = 0
    pad_idx = 0
    for f in sorted_fields:
        off = f["offset"]
        name = sanitize(f["name"])
        if off > prev_end:
            lines.append("  char _pad%d[%d];" % (pad_idx, off - prev_end))
            pad_idx += 1
        elif off < prev_end:
            continue  # overlapping, skip
        lines.append("  void* %s;" % name)
        prev_end = off + 8

    if prev_end < struct_size:
        lines.append("  char _pad_tail[%d];" % (struct_size - prev_end))

    lines.append("};")
    return "\n".join(lines)


def build_class_struct(sname, size, fields, pointer_size):
    """Build a Dart class struct as C declaration."""
    field_sz = pointer_size
    field_type = "int" if pointer_size == 4 else "void*"

    sorted_fields = sorted(fields, key=lambda f: f.get("byte_offset", 0))

    lines = ["struct %s {" % sname]
    prev_end = 0
    pad_idx = 0
    for f in sorted_fields:
        off = f.get("byte_offset", 0)
        fname = sanitize(f.get("name", "field_%x" % off))
        if off < prev_end:
            continue
        if off > prev_end:
            lines.append("  char _pad%d[%d];" % (pad_idx, off - prev_end))
            pad_idx += 1
        if off + field_sz <= size:
            lines.append("  %s %s;" % (field_type, fname))
            prev_end = off + field_sz
        else:
            prev_end = off

    if prev_end < size:
        lines.append("  char _pad_tail[%d];" % (size - prev_end))

    lines.append("};")
    return "\n".join(lines)


def build_function_prototype(name, owner, param_count, struct_names):
    """Build C function prototype. Returns None if no params to apply."""
    cname = sanitize(name)
    params = []

    if owner:
        if owner in struct_names:
            params.append("struct %s* this" % struct_names[owner])
        else:
            params.append("void* this")

    for i in range(param_count):
        params.append("void* p%d" % i)

    if not params:
        return "void* __fastcall %s(void);" % cname

    return "void* __fastcall %s(%s);" % (cname, ", ".join(params))


def _retype_ida_registers(cfunc, ea, ida_hexrays, has_thr_fields):
    """Rename and type Dart register variables in Hex-Rays decompilation.

    64-bit registers:
      x15 → SHADOW_SP (long*)   — indexed stack access: SHADOW_SP[-2]
      x21 → DT        (long)    — dispatch table
      x22 → DART_NULL (long)    — null sentinel
      x26 → THR       (DartThread*) — struct field resolution
      x27 → PP        (long*)   — indexed pool access: PP[8]
      x28 → HEAP_BASE (long)    — compressed pointer base
      x29 → FP        (long)    — frame pointer
      x30 → LR        (long)    — return address

    Also handles 32-bit subregister variants (w15, w22, etc.).

    Returns True if any symbols were retyped (caller should re-decompile).
    """
    import ida_typeinf

    # Build typed tinfo objects once.
    long_tinfo = ida_typeinf.tinfo_t()
    long_tinfo.create_simple_type(ida_typeinf.BTF_INT64)

    long_ptr_tinfo = ida_typeinf.tinfo_t()
    long_ptr_tinfo.create_ptr(long_tinfo)

    int_tinfo = ida_typeinf.tinfo_t()
    int_tinfo.create_simple_type(ida_typeinf.BTF_INT32)

    thr_ptr_tinfo = None
    if has_thr_fields:
        thr_tinfo = ida_typeinf.tinfo_t()
        if thr_tinfo.get_named_type(None, "DartThread"):
            thr_ptr_tinfo = ida_typeinf.tinfo_t()
            thr_ptr_tinfo.create_ptr(thr_tinfo)

    # Map register name → (display_name, tinfo or None).
    RENAMES = {
        # 64-bit
        "x15": ("SHADOW_SP", long_ptr_tinfo),
        "x21": ("DT",        long_tinfo),
        "x22": ("DART_NULL",  long_tinfo),
        "x26": ("THR",        thr_ptr_tinfo),
        "x27": ("PP",         long_ptr_tinfo),
        "x28": ("HEAP_BASE",  long_tinfo),
        "x29": ("FP",         long_tinfo),
        "x30": ("LR",         long_tinfo),
        # 32-bit subregisters
        "w15": ("SHADOW_SP",  int_tinfo),
        "w21": ("DT",         int_tinfo),
        "w22": ("DART_NULL",  int_tinfo),
        "w26": ("THR",        int_tinfo),
        "w27": ("PP",         int_tinfo),
        "w28": ("HEAP_BASE",  int_tinfo),
        "w29": ("FP",         int_tinfo),
        "w30": ("LR",         int_tinfo),
    }

    renamed = False
    try:
        for lvar in cfunc.lvars:
            loc = lvar.location
            if not loc.is_reg1():
                continue
            mreg = loc.reg1()
            try:
                reg_name = ida_hexrays.get_mreg_name(mreg, lvar.width)
            except Exception:
                continue
            if not reg_name:
                continue

            entry = RENAMES.get(reg_name)
            if entry is None:
                continue

            new_name, new_type = entry
            lvar.name = new_name
            if new_type is not None:
                lvar.set_lvar_type(new_type)
            renamed = True

        if renamed:
            cfunc.save_user_lvars()
    except Exception:
        pass

    return renamed


if __name__ == "__main__":
    main()
